[options]
addons_path = /app/odoo/addons,/app/custom-addons,/app/custom-addons/social_addons_18
admin_passwd = $pbkdf2-sha512$600000$qbVWau0dA4Dw/n9PqRUipA$lG1NW.XWqiMKz0oEF2m42tPM8FPjyoDrp8ZZE0BL0TJspCxbL8U5rQD.BK1L.u7MZjF6tRC1xlKzXAsyYTczbg
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
db_name = db01
